export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      organizations: { Row: { id: string; name: string; industry: string; timezone: string; currency: string; status: string; created_at: string; updated_at: string; client_code: string | null }; Insert: Partial<Database['public']['Tables']['organizations']['Row']> & { name: string; industry: string; timezone: string; currency: string; status: string }; Update: Partial<Database['public']['Tables']['organizations']['Row']> }
      branches: { Row: { id: string; organization_id: string; name: string; code: string; address: string | null; city: string | null; state: string | null; country: string; status: string; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['branches']['Row']> & { organization_id: string; name: string; code: string; country: string; status: string }; Update: Partial<Database['public']['Tables']['branches']['Row']> }
      customers: { Row: { id: string; organization_id: string; branch_id: string | null; name: string; company_name: string | null; email: string | null; phone: string | null; address: string | null; city: string | null; state: string | null; country: string; tax_id: string | null; status: string; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['customers']['Row']> & { organization_id: string; name: string; country: string; status: string }; Update: Partial<Database['public']['Tables']['customers']['Row']> }
      projects: { Row: { id: string; organization_id: string; branch_id: string; customer_id: string | null; name: string; code: string | null; description: string | null; project_value: number; budget: number; start_date: string | null; end_date: string | null; status: string; created_by: string | null; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['projects']['Row']> & { organization_id: string; branch_id: string; name: string; project_value: number; budget: number; status: string }; Update: Partial<Database['public']['Tables']['projects']['Row']> }
      project_sites: { Row: { id: string; organization_id: string; project_id: string; name: string; address: string | null; city: string | null; state: string | null; country: string; latitude: number | null; longitude: number | null; status: string; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['project_sites']['Row']> & { organization_id: string; project_id: string; name: string; country: string; status: string }; Update: Partial<Database['public']['Tables']['project_sites']['Row']> }
      tasks: { Row: { id: string; organization_id: string; project_id: string; site_id: string | null; title: string; description: string | null; assigned_to: string | null; priority: string; due_date: string | null; status: string; completed_at: string | null; created_by: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['tasks']['Row']> & { organization_id: string; project_id: string; title: string; priority: string; status: string }; Update: Partial<Database['public']['Tables']['tasks']['Row']> }
      daily_progress: { Row: { id: string; organization_id: string; project_id: string; site_id: string | null; progress_date: string; progress_percent: number | null; notes: string | null; issues: string | null; weather: string | null; created_by: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['daily_progress']['Row']> & { organization_id: string; project_id: string; progress_date: string }; Update: Partial<Database['public']['Tables']['daily_progress']['Row']> }
      daily_progress_items: { Row: { id: string; daily_progress_id: string; description: string; quantity: number | null; unit: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['daily_progress_items']['Row']> & { daily_progress_id: string; description: string }; Update: Partial<Database['public']['Tables']['daily_progress_items']['Row']> }
      daily_progress_photos: { Row: { id: string; daily_progress_id: string; storage_path: string; caption: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['daily_progress_photos']['Row']> & { daily_progress_id: string; storage_path: string }; Update: Partial<Database['public']['Tables']['daily_progress_photos']['Row']> }
      workers: { Row: { id: string; organization_id: string; branch_id: string | null; name: string; phone: string | null; role: string | null; worker_type: string; daily_rate: number; status: string; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['workers']['Row']> & { organization_id: string; name: string; worker_type: string; daily_rate: number; status: string }; Update: Partial<Database['public']['Tables']['workers']['Row']> }
      attendance: { Row: { id: string; organization_id: string; project_id: string; worker_id: string; attendance_date: string; status: string; hours: number | null; notes: string | null; created_by: string | null; created_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['attendance']['Row']> & { organization_id: string; project_id: string; worker_id: string; attendance_date: string; status: string }; Update: Partial<Database['public']['Tables']['attendance']['Row']> }
      labour_allocations: { Row: { id: string; organization_id: string; project_id: string; worker_id: string; allocation_date: string; hours: number | null; cost: number; notes: string | null; created_by: string | null; created_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['labour_allocations']['Row']> & { organization_id: string; project_id: string; worker_id: string; allocation_date: string; cost: number }; Update: Partial<Database['public']['Tables']['labour_allocations']['Row']> }
      materials: { Row: { id: string; organization_id: string; name: string; code: string | null; category: string | null; unit: string; reorder_level: number; status: string; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['materials']['Row']> & { organization_id: string; name: string; unit: string; reorder_level: number; status: string }; Update: Partial<Database['public']['Tables']['materials']['Row']> }
      project_materials: { Row: { id: string; organization_id: string; project_id: string; material_id: string; opening_quantity: number; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['project_materials']['Row']> & { organization_id: string; project_id: string; material_id: string; opening_quantity: number }; Update: Partial<Database['public']['Tables']['project_materials']['Row']> }
      material_transactions: { Row: { id: string; organization_id: string; project_id: string; material_id: string; transaction_type: string; quantity: number; unit: string; reference_type: string | null; reference_id: string | null; transaction_date: string; notes: string | null; created_by: string | null; created_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['material_transactions']['Row']> & { organization_id: string; project_id: string; material_id: string; transaction_type: string; quantity: number; unit: string; transaction_date: string }; Update: Partial<Database['public']['Tables']['material_transactions']['Row']> }
      material_requests: { Row: { id: string; organization_id: string; project_id: string; requested_by: string | null; request_date: string; status: string; notes: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['material_requests']['Row']> & { organization_id: string; project_id: string; request_date: string; status: string }; Update: Partial<Database['public']['Tables']['material_requests']['Row']> }
      material_request_items: { Row: { id: string; material_request_id: string; material_id: string; quantity: number; unit: string; created_at: string }; Insert: Partial<Database['public']['Tables']['material_request_items']['Row']> & { material_request_id: string; material_id: string; quantity: number; unit: string }; Update: Partial<Database['public']['Tables']['material_request_items']['Row']> }
      vendors: { Row: { id: string; organization_id: string; branch_id: string | null; name: string; company_name: string | null; email: string | null; phone: string | null; address: string | null; city: string | null; state: string | null; country: string; tax_id: string | null; status: string; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['vendors']['Row']> & { organization_id: string; name: string; country: string; status: string }; Update: Partial<Database['public']['Tables']['vendors']['Row']> }
      vendor_quotations: { Row: { id: string; organization_id: string; project_id: string | null; vendor_id: string; quotation_number: string | null; quotation_date: string; valid_until: string | null; total_amount: number; status: string; created_by: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['vendor_quotations']['Row']> & { organization_id: string; vendor_id: string; quotation_date: string; total_amount: number; status: string }; Update: Partial<Database['public']['Tables']['vendor_quotations']['Row']> }
      vendor_quotation_items: { Row: { id: string; vendor_quotation_id: string; material_id: string | null; description: string; quantity: number; unit: string | null; unit_price: number; tax_amount: number; total_amount: number; created_at: string }; Insert: Partial<Database['public']['Tables']['vendor_quotation_items']['Row']> & { vendor_quotation_id: string; description: string; quantity: number; unit_price: number; tax_amount: number; total_amount: number }; Update: Partial<Database['public']['Tables']['vendor_quotation_items']['Row']> }
      purchase_orders: { Row: { id: string; organization_id: string; branch_id: string | null; project_id: string | null; vendor_id: string; po_number: string; po_date: string; expected_date: string | null; subtotal: number; tax_amount: number; total_amount: number; status: string; created_by: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['purchase_orders']['Row']> & { organization_id: string; vendor_id: string; po_number: string; po_date: string; subtotal: number; tax_amount: number; total_amount: number; status: string }; Update: Partial<Database['public']['Tables']['purchase_orders']['Row']> }
      purchase_order_items: { Row: { id: string; purchase_order_id: string; material_id: string | null; description: string; ordered_quantity: number; received_quantity: number; unit: string | null; unit_price: number; total_amount: number; created_at: string }; Insert: Partial<Database['public']['Tables']['purchase_order_items']['Row']> & { purchase_order_id: string; description: string; ordered_quantity: number; received_quantity: number; unit_price: number; total_amount: number }; Update: Partial<Database['public']['Tables']['purchase_order_items']['Row']> }
      goods_receipts: { Row: { id: string; organization_id: string; purchase_order_id: string; receipt_number: string; receipt_date: string; notes: string | null; received_by: string | null; created_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['goods_receipts']['Row']> & { organization_id: string; purchase_order_id: string; receipt_number: string; receipt_date: string }; Update: Partial<Database['public']['Tables']['goods_receipts']['Row']> }
      goods_receipt_items: { Row: { id: string; goods_receipt_id: string; purchase_order_item_id: string; quantity: number; unit: string; created_at: string }; Insert: Partial<Database['public']['Tables']['goods_receipt_items']['Row']> & { goods_receipt_id: string; purchase_order_item_id: string; quantity: number; unit: string }; Update: Partial<Database['public']['Tables']['goods_receipt_items']['Row']> }
      expenses: { Row: { id: string; organization_id: string; branch_id: string | null; project_id: string | null; category_id: string | null; expense_date: string; description: string; amount: number; payment_method: string | null; status: string; created_by: string | null; approved_by: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['expenses']['Row']> & { organization_id: string; expense_date: string; description: string; amount: number; status: string }; Update: Partial<Database['public']['Tables']['expenses']['Row']> }
      expense_categories: { Row: { id: string; organization_id: string; name: string; status: string; created_at: string }; Insert: Partial<Database['public']['Tables']['expense_categories']['Row']> & { organization_id: string; name: string; status: string }; Update: Partial<Database['public']['Tables']['expense_categories']['Row']> }
      quotations: { Row: { id: string; organization_id: string; branch_id: string | null; customer_id: string; project_id: string | null; quotation_number: string; quotation_date: string; valid_until: string | null; subtotal: number; discount_amount: number; tax_amount: number; total_amount: number; status: string; created_by: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['quotations']['Row']> & { organization_id: string; customer_id: string; quotation_number: string; quotation_date: string; subtotal: number; discount_amount: number; tax_amount: number; total_amount: number; status: string }; Update: Partial<Database['public']['Tables']['quotations']['Row']> }
      quotation_items: { Row: { id: string; quotation_id: string; description: string; quantity: number; unit: string | null; unit_price: number; discount_amount: number; tax_amount: number; total_amount: number; created_at: string }; Insert: Partial<Database['public']['Tables']['quotation_items']['Row']> & { quotation_id: string; description: string; quantity: number; unit_price: number; discount_amount: number; tax_amount: number; total_amount: number }; Update: Partial<Database['public']['Tables']['quotation_items']['Row']> }
      quotation_revisions: { Row: { id: string; quotation_id: string; revision_number: number; snapshot: Json; created_by: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['quotation_revisions']['Row']> & { quotation_id: string; revision_number: number; snapshot: Json }; Update: Partial<Database['public']['Tables']['quotation_revisions']['Row']> }
      invoices: { Row: { id: string; organization_id: string; branch_id: string | null; project_id: string | null; customer_id: string; quotation_id: string | null; invoice_number: string; invoice_date: string; due_date: string | null; subtotal: number; discount_amount: number; tax_amount: number; total_amount: number; status: string; created_by: string | null; created_at: string; updated_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['invoices']['Row']> & { organization_id: string; customer_id: string; invoice_number: string; invoice_date: string; subtotal: number; discount_amount: number; tax_amount: number; total_amount: number; status: string }; Update: Partial<Database['public']['Tables']['invoices']['Row']> }
      invoice_items: { Row: { id: string; invoice_id: string; description: string; quantity: number; unit: string | null; unit_price: number; tax_amount: number; total_amount: number; created_at: string }; Insert: Partial<Database['public']['Tables']['invoice_items']['Row']> & { invoice_id: string; description: string; quantity: number; unit_price: number; tax_amount: number; total_amount: number }; Update: Partial<Database['public']['Tables']['invoice_items']['Row']> }
      payments: { Row: { id: string; organization_id: string; invoice_id: string; payment_date: string; amount: number; payment_method: string | null; reference_number: string | null; notes: string | null; recorded_by: string | null; created_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['payments']['Row']> & { organization_id: string; invoice_id: string; payment_date: string; amount: number }; Update: Partial<Database['public']['Tables']['payments']['Row']> }
      documents: { Row: { id: string; organization_id: string; branch_id: string | null; project_id: string | null; name: string; document_type: string | null; storage_path: string; mime_type: string | null; file_size: number | null; uploaded_by: string | null; created_at: string; is_setup_data: boolean }; Insert: Partial<Database['public']['Tables']['documents']['Row']> & { organization_id: string; name: string; storage_path: string }; Update: Partial<Database['public']['Tables']['documents']['Row']> }
      notifications: { Row: { id: string; organization_id: string; user_id: string; type: string; title: string; message: string; entity_type: string | null; entity_id: string | null; read_at: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['notifications']['Row']> & { organization_id: string; user_id: string; type: string; title: string; message: string }; Update: Partial<Database['public']['Tables']['notifications']['Row']> }
      notification_events: { Row: { id: string; organization_id: string; event_type: string; entity_type: string | null; entity_id: string | null; payload: Json; processed_at: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['notification_events']['Row']> & { organization_id: string; event_type: string; payload: Json }; Update: Partial<Database['public']['Tables']['notification_events']['Row']> }
      audit_logs: { Row: { id: string; organization_id: string; user_id: string | null; action: string; entity_type: string; entity_id: string | null; old_values: Json | null; new_values: Json | null; created_at: string }; Insert: Partial<Database['public']['Tables']['audit_logs']['Row']> & { organization_id: string; action: string; entity_type: string }; Update: Partial<Database['public']['Tables']['audit_logs']['Row']> }
      organization_members: { Row: { id: string; organization_id: string; user_id: string; role_id: string; status: string; joined_at: string | null; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['organization_members']['Row']> & { organization_id: string; user_id: string; role_id: string; status: string }; Update: Partial<Database['public']['Tables']['organization_members']['Row']> }
      roles: { Row: { id: string; organization_id: string; name: string; description: string | null; is_system: boolean; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['roles']['Row']> & { organization_id: string; name: string; is_system: boolean }; Update: Partial<Database['public']['Tables']['roles']['Row']> }
      permissions: { Row: { id: string; code: string; name: string; description: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['permissions']['Row']> & { code: string; name: string }; Update: Partial<Database['public']['Tables']['permissions']['Row']> }
      role_permissions: { Row: { role_id: string; permission_id: string; created_at: string }; Insert: Partial<Database['public']['Tables']['role_permissions']['Row']> & { role_id: string; permission_id: string }; Update: Partial<Database['public']['Tables']['role_permissions']['Row']> }
      users: { Row: { id: string; full_name: string | null; phone: string | null; avatar_url: string | null; status: string; created_at: string; updated_at: string; platform_role: string }; Insert: Partial<Database['public']['Tables']['users']['Row']> & { id: string; status: string; platform_role: string }; Update: Partial<Database['public']['Tables']['users']['Row']> }
      project_members: { Row: { project_id: string; user_id: string; role_id: string | null; created_at: string }; Insert: Partial<Database['public']['Tables']['project_members']['Row']> & { project_id: string; user_id: string }; Update: Partial<Database['public']['Tables']['project_members']['Row']> }
      member_branch_access: { Row: { member_id: string; branch_id: string; created_at: string }; Insert: Partial<Database['public']['Tables']['member_branch_access']['Row']> & { member_id: string; branch_id: string }; Update: Partial<Database['public']['Tables']['member_branch_access']['Row']> }
      task_dependencies: { Row: { task_id: string; depends_on_task_id: string; created_at: string }; Insert: Partial<Database['public']['Tables']['task_dependencies']['Row']> & { task_id: string; depends_on_task_id: string }; Update: Partial<Database['public']['Tables']['task_dependencies']['Row']> }
      setup_extension_requests: { Row: { id: string; organization_id: string; requested_by: string; requested_days: number; reason: string | null; status: string; reviewed_by: string | null; reviewed_at: string | null; review_notes: string | null; created_at: string; updated_at: string }; Insert: Partial<Database['public']['Tables']['setup_extension_requests']['Row']> & { organization_id: string; requested_by: string; requested_days: number; status: string }; Update: Partial<Database['public']['Tables']['setup_extension_requests']['Row']> }
      workspace_lifecycle: { Row: { organization_id: string; mode: string; setup_started_at: string; setup_expires_at: string; go_live_at: string | null; go_live_by: string | null; updated_at: string }; Insert: Partial<Database['public']['Tables']['workspace_lifecycle']['Row']> & { organization_id: string; mode: string; setup_started_at: string; setup_expires_at: string }; Update: Partial<Database['public']['Tables']['workspace_lifecycle']['Row']> }
      workspace_lifecycle_events: { Row: { id: string; organization_id: string; event_type: string; performed_by: string | null; previous_mode: string | null; new_mode: string | null; metadata: Json; created_at: string }; Insert: Partial<Database['public']['Tables']['workspace_lifecycle_events']['Row']> & { organization_id: string; event_type: string; metadata: Json }; Update: Partial<Database['public']['Tables']['workspace_lifecycle_events']['Row']> }
      storage_cleanup_queue: { Row: { id: string; organization_id: string; storage_path: string; source_type: string; source_id: string; created_at: string; processed_at: string | null; status: string; error_message: string | null }; Insert: Partial<Database['public']['Tables']['storage_cleanup_queue']['Row']> & { organization_id: string; storage_path: string; source_type: string; source_id: string; status: string }; Update: Partial<Database['public']['Tables']['storage_cleanup_queue']['Row']> }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
