'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/browser'

type Vendor = { id: string; name: string; company_name: string | null; phone: string | null; email: string | null; status: string }

export default function VendorsPage() {
  const router = useRouter(); const [items,setItems]=useState<Vendor[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [name,setName]=useState(''); const [company,setCompany]=useState(''); const [phone,setPhone]=useState(''); const [email,setEmail]=useState('')
  async function load(){const s=createClient(); const {data:u}=await s.auth.getUser(); if(!u.user){router.replace('/login');return} const {data,error}=await s.from('vendors').select('id,name,company_name,phone,email,status').order('created_at',{ascending:false}); if(error)setMessage(error.message); else setItems((data??[]) as Vendor[]); setLoading(false)}
  useEffect(()=>{load()},[])
  async function add(e:FormEvent){e.preventDefault();setMessage('');if(!name.trim()){setMessage('Vendor name is required.');return}setSaving(true);const s=createClient();const uid=(await s.auth.getUser()).data.user?.id??'';const {data:m}=await s.from('organization_members').select('organization_id').eq('user_id',uid).eq('status','active').limit(1).maybeSingle();if(!m){setMessage('Your workspace membership could not be found.');setSaving(false);return}const {error}=await s.from('vendors').insert({organization_id:m.organization_id,name:name.trim(),company_name:company.trim()||null,phone:phone.trim()||null,email:email.trim()||null,status:'active'});if(error)setMessage(error.message);else{name&&setName('');setCompany('');setPhone('');setEmail('');await load()}setSaving(false)}
  const input=(value:string,setter:(v:string)=>void,type='text')=><input type={type} value={value} onChange={e=>setter(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-slate-900 outline-none focus:border-blue-600"/>
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><div><button onClick={()=>router.push('/')} className="text-sm font-bold tracking-widest text-blue-600">BUILDOS</button><div className="text-xs text-slate-500">Vendors</div></div><button onClick={()=>router.push('/')} className="text-sm text-slate-600">Dashboard</button></div></header><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><h1 className="text-3xl font-bold">Vendors</h1><p className="mt-1 text-sm text-slate-500">Manage suppliers and service providers.</p><div className="mt-6 grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={add} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Add vendor</h2><label className="mt-4 block text-sm font-medium text-slate-700">Name{input(name,setName)}</label><label className="mt-3 block text-sm font-medium text-slate-700">Company{input(company,setCompany)}</label><label className="mt-3 block text-sm font-medium text-slate-700">Phone{input(phone,setPhone,'tel')}</label><label className="mt-3 block text-sm font-medium text-slate-700">Email{input(email,setEmail,'email')}</label>{message&&<p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm">{message}</p>}<button disabled={saving} className="mt-4 w-full rounded-lg bg-blue-600 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{saving?'Saving...':'Add vendor'}</button></form><section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4 font-semibold">Vendor list</div>{loading?<p className="p-5 text-sm text-slate-500">Loading vendors...</p>:items.length===0?<div className="p-8 text-center text-sm text-slate-500">No vendors yet.</div>:<div className="divide-y divide-slate-100">{items.map(v=><div key={v.id} className="flex flex-col gap-2 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{v.name}</p><p className="text-sm text-slate-500">{v.company_name||'Supplier'}{v.phone?` · ${v.phone}`:''}{v.email?` · ${v.email}`:''}</p></div><span className="w-fit rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{v.status}</span></div>)}</div>}</section></div></div></main>
}
